"""
Trade Ticket Schema — CUFA Equity Report v16

Single source of truth for the Trade Ticket YAML contract.
All fields are typed and validated. Downstream consumers
(QuantPipeline, backtest_hook, feedback loop) depend on this schema.

YAML Output Example:
    ticker: 329180.KS
    opinion: BUY
    entry_price: 475000
    stop_loss: 410000
    target_price: 528750
    horizon_months: 12
    position_size_pct: 5.0
    risk_reward: 1.42
    kill_conditions:
      - "수주잔고 YoY -20% 이하로 붕괴"
      - ...
    catalyst_timeline:
      - date: "2025Q3"
        event: "LNG 운반선 대규모 슬롯 계약"
    backtest_engine: open-trading-api/QuantPipeline
    report_version: v16
    generated_at: "2026-04-12"
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class TradeOpinion(str, Enum):
    BUY = "BUY"
    HOLD = "HOLD"
    SELL = "SELL"
    WATCH = "WATCH"         # 모니터링 (진입 조건 미달)
    AVOID = "AVOID"         # 명시적 회피


@dataclass(frozen=True)
class CatalystEvent:
    date: str               # e.g. "2025Q3", "2026-01"
    event: str              # 트리거 이벤트 설명
    upside_delta_pct: float | None = None   # 발생 시 TP 영향 (%)


@dataclass(frozen=True)
class ScenarioBand:
    bear_price: int
    base_price: int
    bull_price: int
    bear_prob: float        # 0.0 ~ 1.0
    base_prob: float
    bull_prob: float


@dataclass
class TradeTicket:
    """
    Machine-readable Trade Ticket.
    Generated by generator.py, consumed by backtest_hook.py and feedback.py.
    """
    # === Identity ===
    ticker: str                             # e.g. "329180.KS"
    company_name: str                       # e.g. "HD현대중공업"
    report_version: str = "v16"

    # === Opinion & Targets ===
    opinion: TradeOpinion = TradeOpinion.HOLD
    entry_price: int = 0                    # 진입 기준가 (원)
    stop_loss: int = 0                      # 손절가 (원)
    target_price: int = 0                   # 목표주가 (원)
    horizon_months: int = 12               # 투자 기간 (개월)

    # === Sizing ===
    position_size_pct: float = 2.0          # 포트폴리오 비중 (%)
    risk_reward: float = 0.0               # (TP - Entry) / (Entry - SL)

    # === Kill Conditions (최소 3개) ===
    kill_conditions: list[str] = field(default_factory=list)

    # === Catalysts (최소 3개) ===
    catalyst_timeline: list[CatalystEvent] = field(default_factory=list)

    # === Scenario ===
    scenario: ScenarioBand | None = None

    # === Backtest Integration ===
    backtest_engine: str = "open-trading-api/QuantPipeline"
    backtest_config: dict[str, Any] = field(default_factory=dict)

    # === Metadata ===
    generated_at: str = ""                  # ISO date string
    analyst: str = "Luxon AI / CUFA"
    data_sources: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

class TradeTicketValidationError(ValueError):
    pass


def validate_trade_ticket(ticket: TradeTicket) -> list[str]:
    """
    Validate a TradeTicket against v16 Evaluator v3 criteria.

    Returns:
        List of error strings. Empty list = PASS.
    """
    errors: list[str] = []

    # Binary Criteria
    if not ticket.ticker:
        errors.append("TICKER: 비어있음")
    if ticket.opinion not in TradeOpinion:
        errors.append(f"OPINION: 유효하지 않음 ({ticket.opinion})")
    if ticket.stop_loss <= 0:
        errors.append("STOP_LOSS: 0 이하 — 반드시 손절가 설정")
    if ticket.target_price <= 0:
        errors.append("TARGET_PRICE: 0 이하")
    if ticket.entry_price <= 0:
        errors.append("ENTRY_PRICE: 0 이하")
    if ticket.position_size_pct <= 0 or ticket.position_size_pct > 20:
        errors.append(f"POSITION_SIZE_PCT: {ticket.position_size_pct}% — 0~20% 범위 필요")
    if len(ticket.kill_conditions) < 3:
        errors.append(f"KILL_CONDITIONS: {len(ticket.kill_conditions)}개 — 최소 3개 필요")
    if len(ticket.catalyst_timeline) < 3:
        errors.append(f"CATALYST_TIMELINE: {len(ticket.catalyst_timeline)}개 — 최소 3개 필요")
    if not ticket.backtest_engine:
        errors.append("BACKTEST_ENGINE: 미지정")
    if not ticket.data_sources:
        errors.append("DATA_SOURCES: 출처 미기재")

    # Logical Consistency
    if ticket.entry_price > 0 and ticket.stop_loss > 0:
        if ticket.opinion == TradeOpinion.BUY and ticket.stop_loss >= ticket.entry_price:
            errors.append("LOGIC: BUY인데 손절가 ≥ 진입가")
        if ticket.opinion == TradeOpinion.SELL and ticket.stop_loss <= ticket.entry_price:
            errors.append("LOGIC: SELL인데 손절가 ≤ 진입가")

    # Risk/Reward
    if ticket.entry_price > 0 and ticket.stop_loss > 0 and ticket.target_price > 0:
        numerator = abs(ticket.target_price - ticket.entry_price)
        denominator = abs(ticket.entry_price - ticket.stop_loss)
        if denominator > 0:
            computed_rr = round(numerator / denominator, 2)
            if abs(computed_rr - ticket.risk_reward) > 0.1:
                errors.append(
                    f"RISK_REWARD: 기재값 {ticket.risk_reward} ≠ 계산값 {computed_rr}"
                )

    return errors


def ticket_to_yaml(ticket: TradeTicket) -> str:
    """Serialize TradeTicket to YAML string (no external dependency)."""
    def _fmt(v: Any, indent: int = 0) -> str:
        pad = "  " * indent
        if isinstance(v, list):
            if not v:
                return "[]"
            lines = []
            for item in v:
                if isinstance(item, (CatalystEvent,)):
                    lines.append(f"\n{pad}  - date: \"{item.date}\"")
                    lines.append(f"{pad}    event: \"{item.event}\"")
                    if item.upside_delta_pct is not None:
                        lines.append(f"{pad}    upside_delta_pct: {item.upside_delta_pct}")
                elif isinstance(item, dict):
                    inner = "\n".join(f"{pad}    {k}: {v2}" for k, v2 in item.items())
                    lines.append(f"\n{pad}  -\n{inner}")
                else:
                    lines.append(f"\n{pad}  - \"{item}\"")
            return "".join(lines)
        if isinstance(v, dict):
            if not v:
                return "{}"
            lines = ["\n"]
            for k2, v2 in v.items():
                lines.append(f"{pad}  {k2}: {v2}\n")
            return "".join(lines)
        if isinstance(v, str):
            return f'"{v}"'
        if isinstance(v, bool):
            return str(v).lower()
        return str(v)

    lines = ["# CUFA Trade Ticket v16", f"# Generated: {ticket.generated_at}", ""]
    lines.append(f"ticker: {ticket.ticker}")
    lines.append(f"company: {ticket.company_name}")
    lines.append(f"opinion: {ticket.opinion.value}")
    lines.append(f"entry_price: {ticket.entry_price}")
    lines.append(f"stop_loss: {ticket.stop_loss}")
    lines.append(f"target_price: {ticket.target_price}")
    lines.append(f"horizon_months: {ticket.horizon_months}")
    lines.append(f"position_size_pct: {ticket.position_size_pct}")
    lines.append(f"risk_reward: {ticket.risk_reward}")
    lines.append(f"backtest_engine: {ticket.backtest_engine}")
    lines.append(f"report_version: {ticket.report_version}")
    lines.append(f"analyst: {ticket.analyst}")
    lines.append("")
    lines.append("kill_conditions:")
    for kc in ticket.kill_conditions:
        lines.append(f'  - "{kc}"')
    lines.append("")
    lines.append("catalyst_timeline:")
    for cat in ticket.catalyst_timeline:
        lines.append(f'  - date: "{cat.date}"')
        lines.append(f'    event: "{cat.event}"')
        if cat.upside_delta_pct is not None:
            lines.append(f"    upside_delta_pct: {cat.upside_delta_pct}")
    lines.append("")
    if ticket.scenario:
        s = ticket.scenario
        lines.append("scenario:")
        lines.append(f"  bear: {{price: {s.bear_price}, prob: {s.bear_prob}}}")
        lines.append(f"  base: {{price: {s.base_price}, prob: {s.base_prob}}}")
        lines.append(f"  bull: {{price: {s.bull_price}, prob: {s.bull_prob}}}")
        lines.append("")
    if ticket.data_sources:
        lines.append("data_sources:")
        for ds in ticket.data_sources:
            lines.append(f'  - "{ds}"')
    if ticket.backtest_config:
        lines.append("")
        lines.append("backtest_config:")
        for k, v in ticket.backtest_config.items():
            lines.append(f"  {k}: {v}")
    return "\n".join(lines)
